# Generated by Django 4.2.5 on 2023-10-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_roomreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomReservation',
        ),
    ]
